[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc = "0.8.27"
# evm_version = "cancun"
auto_detect_solc = true
via_ir = true
optimizer = true
optimizer_runs = 200

# Allow importing from different solidity versions
allow_paths = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
